package medi.master.core.domain.medical.product.model

data class MedicalDetailItem(
    val itemSequence: String,
    val itemName: String,
    val enterpriseName: String,
    val itemPermitDate: String,
    val consignedManufacturer: String? = null,
    val otcClassification: String? = null,
    val appearanceDescription: String? = null,
    val barCodes: String,
    val materialName: String,
    val efficacyDocumentUrl: String,
    val dosageDocumentUrl: String,
    val precautionsDocumentUrl: String,
    val insertDocumentUrl: String,
    val storageMethod: String,
    val validityPeriod: String,
    val reevaluationTarget: String?,
    val reevaluationDate: String?,
    val packagingUnit: String,
    val ediCode: String?,
    val permitKind: String,
    val enterpriseNumber: String,
    val manufacturingType: String,
    val newDrugClassification: String,
    val industryType: String,
    val cancelDate: String?,
    val cancelStatus: String,
    val lastChangeDate: String,
    val narcoticCategoryCode: String?,
    val historyChanges: String,
    val totalContent: String? = null,
    val efficacyDocuments: Set<MedicalItemArticleData> = emptySet(),
    val dosageDocuments: Set<MedicalItemArticleData> = emptySet(),
    val precautionsDocuments: Set<MedicalItemArticleData> = emptySet(),
    val pediatricDocuments: Set<MedicalItemArticleData> = emptySet(),
    val mainIngredientKor: String,
    val ingredientNamesKor: String,
    val atcCode: String? = null,
    val itemNameEnglish: String,
    val enterpriseNameEnglish: String,
    val mainIngredientEnglish: String,
    val businessRegistrationNumber: String,
    val isRareDrug: String? = null
)
